package model;

public enum CellType {
    UNCHECKED,
    CHECKED_ADJACENT_0,
    CHECKED_ADJACENT_1,
    CHECKED_ADJACENT_2,
    CHECKED_ADJACENT_3,
    CHECKED_ADJACENT_4,
    CHECKED_ADJACENT_5,
    CHECKED_ADJACENT_6,
    CHECKED_MINE
}
